### ISSUE TITLE
analysis of unsupported microscopy system

### ISSUE THREAD

**Issue by IdRose** [hmbotelho/FIS_image_analysis#1]
Could I use images from a different microscope (Nikon) If I rename the files to conform with the output of htmrenamer? Did you see a difference in analysis based on the brand, or is the only issue with the names themselves?
Thank you, much appreciated

**Comment by hmbotelho** [comment]
Hi @IdRose. Yes, the workflow is compatible with images from any microscope. The naming structure implemented in htmrenamer is useful to structure the analysis of images (e.g. group images belonging to the same well) and numerical data (e.g. aggregate and summarize all measurements performed in identical conditions). If you rename your files to conform with the output of htmrenamer you should be able to "plug into" this workflow. We made sure the analysis does not depend on the microscope brand (e.g. [10.1093/bioinformatics/btaa1073](https://doi.org/10.1093/bioinformatics/btaa1073) and [10.1016/S1569-1993(19)30244-9](https://doi.org/10.1016/S1569-1993(19)30244-9).
That being said, if you would to work with me in order to extend the compatibility of htmrenamer to Nikon datasets, just let me know and we can discuss it offline.
Thanks for writing. Cheers.
